eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:9000/eureka
    registry-fetch-interval-seconds: 3
    instance-info-replication-interval-seconds: 3
  instance:
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${spring.application.instance_id:${server.port}}
    prefer-ip-address: true
    lease-expiration-duration-in-seconds: 5
    lease-renewal-interval-in-seconds: 10
    ip-address: 127.0.0.1
